#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=08:00:00
#SBATCH --mem=32000M
#SBATCH --output=model_inference_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate DL2

srun python -m model.run_model pipeline --experiment_name evaluation1 dataset --dataset parti-prompts